CREATE TABLE IF NOT EXISTS `UserAccount` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `CognitoSubject` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `Email` VARCHAR(320) NULL,
    `DisplayName` VARCHAR(255) NULL,
    `AccountStatus` VARCHAR(32) NOT NULL DEFAULT 'Active',
    `LastSignInAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `DeletedAtUtc` DATETIME(6) NULL,
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_UserAccount_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_UserAccount_CognitoSubject` (`CognitoSubject`),
    KEY `Ix_UserAccount_Email` (`Email`(191)),
    KEY `Ix_UserAccount_Status` (`AccountStatus`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Device` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `DeviceKey` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `DisplayName` VARCHAR(255) NOT NULL,
    `Platform` VARCHAR(32) NOT NULL,
    `OperatingSystemVersion` VARCHAR(64) NULL,
    `AppVersion` VARCHAR(64) NULL,
    `SyncCursor` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `LastActivityAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `RetiredAtUtc` DATETIME(6) NULL,
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_Device_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_Device_User_DeviceKey` (`UserId`, `DeviceKey`),
    UNIQUE KEY `Ux_Device_User_Id` (`UserId`, `Id`),
    KEY `Ix_Device_User_LastActivity` (`UserId`, `LastActivityAtUtc`),
    CONSTRAINT `Fk_Device_UserAccount`
        FOREIGN KEY (`UserId`) REFERENCES `UserAccount` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `IdempotencyRecord` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `IdempotencyKey` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `HttpMethod` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `RoutePattern` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `RequestSha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    `ResponseStatusCode` SMALLINT UNSIGNED NULL,
    `ResponseHeadersJson` JSON NULL,
    `ResponseBodyJson` JSON NULL,
    `ExpiresAtUtc` DATETIME(6) NOT NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_IdempotencyRecord_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_IdempotencyRecord_User_Key` (`UserId`, `IdempotencyKey`),
    KEY `Ix_IdempotencyRecord_ExpiresAt` (`ExpiresAtUtc`),
    CONSTRAINT `Fk_IdempotencyRecord_UserAccount`
        FOREIGN KEY (`UserId`) REFERENCES `UserAccount` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `MediaSource` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `DeviceId` BIGINT UNSIGNED NOT NULL,
    `SourceKey` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `DisplayName` VARCHAR(255) NOT NULL,
    `SourceType` VARCHAR(32) NOT NULL,
    `StorageMode` VARCHAR(16) NOT NULL DEFAULT 'Local',
    `PermissionState` VARCHAR(32) NOT NULL DEFAULT 'NotApplicable',
    `SourceStatus` VARCHAR(16) NOT NULL DEFAULT 'Active',
    `SyncPolicyJson` JSON NULL,
    `SyncCursor` VARCHAR(1024) NULL,
    `LastManifestAtUtc` DATETIME(6) NULL,
    `LastSuccessAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `RemovedAtUtc` DATETIME(6) NULL,
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_MediaSource_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_MediaSource_User_Device_SourceKey` (`UserId`, `DeviceId`, `SourceKey`),
    UNIQUE KEY `Ux_MediaSource_User_Id` (`UserId`, `Id`),
    KEY `Ix_MediaSource_User_Mode` (`UserId`, `StorageMode`, `SourceStatus`),
    KEY `Ix_MediaSource_Device_Status` (`DeviceId`, `SourceStatus`),
    CONSTRAINT `Fk_MediaSource_Device`
        FOREIGN KEY (`UserId`, `DeviceId`) REFERENCES `Device` (`UserId`, `Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `MediaAsset` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `ContentSha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    `MediaType` VARCHAR(16) NOT NULL,
    `MimeType` VARCHAR(255) NOT NULL,
    `ByteSize` BIGINT UNSIGNED NOT NULL,
    `WidthPixels` INT UNSIGNED NULL,
    `HeightPixels` INT UNSIGNED NULL,
    `DurationMilliseconds` BIGINT UNSIGNED NULL,
    `CaptureDateTimeLocal` DATETIME(6) NULL,
    `CaptureDateTimeUtc` DATETIME(6) NULL,
    `TimeZone` VARCHAR(64) NULL,
    `UtcOffsetMinutes` SMALLINT NULL,
    `CaptureTimeSource` VARCHAR(32) NULL,
    `CaptureTimeConfidence` DECIMAL(5,4) NULL,
    `MetadataJson` JSON NULL,
    `MetadataVersion` VARCHAR(64) NULL,
    `Category` VARCHAR(255) NULL,
    `CategorySource` VARCHAR(64) NULL,
    `StorageState` VARCHAR(32) NOT NULL DEFAULT 'LocalOnly',
    `S3Bucket` VARCHAR(63) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `OriginalS3ObjectKey` VARCHAR(1024) COLLATE utf8mb4_bin NULL,
    `OriginalS3VersionId` VARCHAR(1024) NULL,
    `OriginalS3ETag` VARCHAR(255) NULL,
    `PreviewS3ObjectKey` VARCHAR(1024) COLLATE utf8mb4_bin NULL,
    `LifecycleState` VARCHAR(32) NOT NULL DEFAULT 'Active',
    `LastProcessedAtUtc` DATETIME(6) NULL,
    `TrashedAtUtc` DATETIME(6) NULL,
    `PurgeAfterUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_MediaAsset_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_MediaAsset_User_ContentSha256` (`UserId`, `ContentSha256`),
    UNIQUE KEY `Ux_MediaAsset_User_Id` (`UserId`, `Id`),
    KEY `Ix_MediaAsset_User_Timeline` (`UserId`, `LifecycleState`, `CaptureDateTimeLocal`, `Id`),
    KEY `Ix_MediaAsset_User_MediaType_Date` (`UserId`, `MediaType`, `CaptureDateTimeLocal`, `Id`),
    KEY `Ix_MediaAsset_User_Category_Date` (`UserId`, `Category`(191), `CaptureDateTimeLocal`),
    KEY `Ix_MediaAsset_User_StorageState` (`UserId`, `StorageState`, `UpdatedAtUtc`),
    KEY `Ix_MediaAsset_PurgeAfter` (`LifecycleState`, `PurgeAfterUtc`),
    CONSTRAINT `Fk_MediaAsset_UserAccount`
        FOREIGN KEY (`UserId`) REFERENCES `UserAccount` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `MediaOccurrence` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `MediaSourceId` BIGINT UNSIGNED NOT NULL,
    `MediaAssetId` BIGINT UNSIGNED NULL,
    `SourceItemId` VARCHAR(512) COLLATE utf8mb4_bin NOT NULL,
    `OriginalFileName` VARCHAR(512) NOT NULL,
    `LocalLocator` TEXT NULL,
    `SourceRevision` VARCHAR(255) NULL,
    `ObservedByteSize` BIGINT UNSIGNED NULL,
    `ObservedModifiedAtUtc` DATETIME(6) NULL,
    `HashStatus` VARCHAR(32) NOT NULL DEFAULT 'Pending',
    `HashFailureCode` VARCHAR(64) NULL,
    `AvailabilityState` VARCHAR(32) NOT NULL DEFAULT 'Available',
    `DeletionState` VARCHAR(32) NOT NULL DEFAULT 'Active',
    `FirstSeenAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `LastSeenAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `DeletedAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_MediaOccurrence_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_MediaOccurrence_Source_SourceItemId` (`MediaSourceId`, `SourceItemId`),
    UNIQUE KEY `Ux_MediaOccurrence_User_Id` (`UserId`, `Id`),
    KEY `Ix_MediaOccurrence_User_Asset` (`UserId`, `MediaAssetId`),
    KEY `Ix_MediaOccurrence_Source_LastSeen` (`MediaSourceId`, `LastSeenAtUtc`),
    KEY `Ix_MediaOccurrence_User_DeletionState` (`UserId`, `DeletionState`, `UpdatedAtUtc`),
    KEY `Ix_MediaOccurrence_User_HashStatus` (`UserId`, `HashStatus`, `UpdatedAtUtc`),
    CONSTRAINT `Fk_MediaOccurrence_MediaSource`
        FOREIGN KEY (`UserId`, `MediaSourceId`) REFERENCES `MediaSource` (`UserId`, `Id`) ON DELETE CASCADE,
    CONSTRAINT `Fk_MediaOccurrence_MediaAsset`
        FOREIGN KEY (`UserId`, `MediaAssetId`) REFERENCES `MediaAsset` (`UserId`, `Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `MediaLocation` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `MediaAssetId` BIGINT UNSIGNED NOT NULL,
    `Latitude` DECIMAL(9,6) NULL,
    `Longitude` DECIMAL(10,6) NULL,
    `AltitudeMeters` DECIMAL(10,3) NULL,
    `AccuracyMeters` DECIMAL(10,3) NULL,
    `LocationDisplayName` VARCHAR(512) NULL,
    `StreetAddress` VARCHAR(512) NULL,
    `OriginalStreetNumber` VARCHAR(32) NULL,
    `Neighborhood` VARCHAR(255) NULL,
    `City` VARCHAR(255) NULL,
    `County` VARCHAR(255) NULL,
    `State` VARCHAR(255) NULL,
    `PostalCode` VARCHAR(32) NULL,
    `Country` VARCHAR(255) NULL,
    `CountryCode` VARCHAR(8) NULL,
    `LocationSource` VARCHAR(32) NULL,
    `Provider` VARCHAR(64) NULL,
    `ProviderPlaceId` VARCHAR(255) NULL,
    `NormalizationRuleVersion` VARCHAR(64) NULL,
    `Confidence` DECIMAL(5,4) NULL,
    `RawProviderJson` JSON NULL,
    `ProviderUpdatedAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_MediaLocation_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_MediaLocation_User_Asset` (`UserId`, `MediaAssetId`),
    KEY `Ix_MediaLocation_User_LatLon` (`UserId`, `Latitude`, `Longitude`),
    KEY `Ix_MediaLocation_User_City_State` (`UserId`, `City`(191), `State`(191)),
    CONSTRAINT `Fk_MediaLocation_MediaAsset`
        FOREIGN KEY (`UserId`, `MediaAssetId`) REFERENCES `MediaAsset` (`UserId`, `Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `MediaDescription` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `MediaAssetId` BIGINT UNSIGNED NOT NULL,
    `Description` LONGTEXT NULL,
    `LanguageCode` VARCHAR(16) NULL,
    `Provider` VARCHAR(64) NOT NULL,
    `Model` VARCHAR(128) NOT NULL,
    `PromptVersion` VARCHAR(64) NOT NULL,
    `Status` VARCHAR(32) NOT NULL DEFAULT 'Queued',
    `IsCurrent` TINYINT(1) NOT NULL DEFAULT 0,
    `FailureCode` VARCHAR(64) NULL,
    `RequestedAtUtc` DATETIME(6) NULL,
    `CompletedAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_MediaDescription_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_MediaDescription_Asset_Version` (`UserId`, `MediaAssetId`, `Provider`, `Model`, `PromptVersion`),
    KEY `Ix_MediaDescription_User_Status` (`UserId`, `Status`, `UpdatedAtUtc`),
    KEY `Ix_MediaDescription_User_Asset_Current` (`UserId`, `MediaAssetId`, `IsCurrent`),
    FULLTEXT KEY `Ix_MediaDescription_FullText` (`Description`),
    CONSTRAINT `Fk_MediaDescription_MediaAsset`
        FOREIGN KEY (`UserId`, `MediaAssetId`) REFERENCES `MediaAsset` (`UserId`, `Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `MediaTranscript` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `MediaAssetId` BIGINT UNSIGNED NOT NULL,
    `Provider` VARCHAR(64) NOT NULL,
    `Model` VARCHAR(128) NOT NULL,
    `ProviderRequestId` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `LanguageCode` VARCHAR(16) NULL,
    `TranscriptText` LONGTEXT NULL,
    `DurationMilliseconds` BIGINT UNSIGNED NULL,
    `Status` VARCHAR(32) NOT NULL DEFAULT 'Queued',
    `IsCurrent` TINYINT(1) NOT NULL DEFAULT 0,
    `FailureCode` VARCHAR(64) NULL,
    `RequestedAtUtc` DATETIME(6) NULL,
    `CompletedAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_MediaTranscript_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_MediaTranscript_Provider_Request` (`UserId`, `Provider`, `ProviderRequestId`),
    UNIQUE KEY `Ux_MediaTranscript_User_Id` (`UserId`, `Id`),
    KEY `Ix_MediaTranscript_User_Status` (`UserId`, `Status`, `UpdatedAtUtc`),
    KEY `Ix_MediaTranscript_User_Asset_Current` (`UserId`, `MediaAssetId`, `IsCurrent`),
    FULLTEXT KEY `Ix_MediaTranscript_FullText` (`TranscriptText`),
    CONSTRAINT `Fk_MediaTranscript_MediaAsset`
        FOREIGN KEY (`UserId`, `MediaAssetId`) REFERENCES `MediaAsset` (`UserId`, `Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `MediaTranscriptSegment` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `MediaTranscriptId` BIGINT UNSIGNED NOT NULL,
    `SequenceNumber` INT UNSIGNED NOT NULL,
    `StartMilliseconds` BIGINT UNSIGNED NOT NULL,
    `EndMilliseconds` BIGINT UNSIGNED NOT NULL,
    `SpeakerLabel` VARCHAR(128) NULL,
    `SegmentText` TEXT NOT NULL,
    `Confidence` DECIMAL(5,4) NULL,
    `WordTimingsJson` JSON NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_MediaTranscriptSegment_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_MediaTranscriptSegment_Transcript_Sequence` (`UserId`, `MediaTranscriptId`, `SequenceNumber`),
    KEY `Ix_MediaTranscriptSegment_Transcript_Time` (`MediaTranscriptId`, `StartMilliseconds`),
    FULLTEXT KEY `Ix_MediaTranscriptSegment_FullText` (`SegmentText`),
    CONSTRAINT `Fk_MediaTranscriptSegment_Transcript`
        FOREIGN KEY (`UserId`, `MediaTranscriptId`) REFERENCES `MediaTranscript` (`UserId`, `Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UploadSession` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `MediaAssetId` BIGINT UNSIGNED NOT NULL,
    `MediaOccurrenceId` BIGINT UNSIGNED NULL,
    `IdempotencyKey` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `ObjectPurpose` VARCHAR(32) NOT NULL,
    `UploadKind` VARCHAR(16) NOT NULL,
    `Status` VARCHAR(32) NOT NULL DEFAULT 'Preparing',
    `ActiveLeaseMarker` TINYINT UNSIGNED NULL DEFAULT 1,
    `LeaseTokenHash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `LeaseOwner` VARCHAR(128) NULL,
    `S3Bucket` VARCHAR(63) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `S3ObjectKey` VARCHAR(1024) COLLATE utf8mb4_bin NOT NULL,
    `S3UploadId` VARCHAR(1024) NULL,
    `ChecksumSha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    `ExpectedByteSize` BIGINT UNSIGNED NOT NULL,
    `UploadedByteSize` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `PartSizeBytes` BIGINT UNSIGNED NULL,
    `PartsJson` JSON NULL,
    `ExpiresAtUtc` DATETIME(6) NOT NULL,
    `CompletedAtUtc` DATETIME(6) NULL,
    `FailureCode` VARCHAR(64) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_UploadSession_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_UploadSession_User_Idempotency` (`UserId`, `IdempotencyKey`),
    UNIQUE KEY `Ux_UploadSession_ActiveLease` (`UserId`, `MediaAssetId`, `ObjectPurpose`, `ActiveLeaseMarker`),
    KEY `Ix_UploadSession_User_Status` (`UserId`, `Status`, `UpdatedAtUtc`),
    KEY `Ix_UploadSession_Status_Expiry` (`Status`, `ExpiresAtUtc`),
    CONSTRAINT `Fk_UploadSession_MediaAsset`
        FOREIGN KEY (`UserId`, `MediaAssetId`) REFERENCES `MediaAsset` (`UserId`, `Id`) ON DELETE CASCADE,
    CONSTRAINT `Fk_UploadSession_MediaOccurrence`
        FOREIGN KEY (`UserId`, `MediaOccurrenceId`) REFERENCES `MediaOccurrence` (`UserId`, `Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ProcessingJob` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `MediaAssetId` BIGINT UNSIGNED NOT NULL,
    `MediaSourceId` BIGINT UNSIGNED NULL,
    `IdempotencyKey` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `JobType` VARCHAR(32) NOT NULL,
    `Status` VARCHAR(32) NOT NULL DEFAULT 'Queued',
    `Provider` VARCHAR(64) NULL,
    `AttemptCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `MaxAttempts` INT UNSIGNED NOT NULL DEFAULT 5,
    `NextAttemptAtUtc` DATETIME(6) NULL,
    `LeaseTokenHash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `LeaseExpiresAtUtc` DATETIME(6) NULL,
    `FailureClass` VARCHAR(32) NULL,
    `FailureCode` VARCHAR(64) NULL,
    `FailureMessage` TEXT NULL,
    `RequestJson` JSON NULL,
    `StartedAtUtc` DATETIME(6) NULL,
    `CompletedAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_ProcessingJob_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_ProcessingJob_User_Idempotency` (`UserId`, `IdempotencyKey`),
    KEY `Ix_ProcessingJob_Status_NextAttempt` (`Status`, `NextAttemptAtUtc`, `Id`),
    KEY `Ix_ProcessingJob_User_Status` (`UserId`, `Status`, `CreatedAtUtc`),
    KEY `Ix_ProcessingJob_User_Asset_Type` (`UserId`, `MediaAssetId`, `JobType`),
    CONSTRAINT `Fk_ProcessingJob_MediaAsset`
        FOREIGN KEY (`UserId`, `MediaAssetId`) REFERENCES `MediaAsset` (`UserId`, `Id`) ON DELETE CASCADE,
    CONSTRAINT `Fk_ProcessingJob_MediaSource`
        FOREIGN KEY (`UserId`, `MediaSourceId`) REFERENCES `MediaSource` (`UserId`, `Id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ProviderUsageMonth` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `Provider` VARCHAR(64) NOT NULL,
    `UsageMonth` DATE NOT NULL,
    `UnitType` VARCHAR(32) NOT NULL,
    `ProcessedUnits` DECIMAL(20,6) UNSIGNED NOT NULL DEFAULT 0,
    `ReservedUnits` DECIMAL(20,6) UNSIGNED NOT NULL DEFAULT 0,
    `HardLimitUnits` DECIMAL(20,6) UNSIGNED NOT NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_ProviderUsageMonth_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_ProviderUsageMonth_User_Provider_Month_Unit` (`UserId`, `Provider`, `UsageMonth`, `UnitType`),
    KEY `Ix_ProviderUsageMonth_User_Month` (`UserId`, `UsageMonth`),
    CONSTRAINT `Fk_ProviderUsageMonth_UserAccount`
        FOREIGN KEY (`UserId`) REFERENCES `UserAccount` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `MediaChange` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `DeviceId` BIGINT UNSIGNED NULL,
    `MediaSourceId` BIGINT UNSIGNED NULL,
    `MediaAssetId` BIGINT UNSIGNED NULL,
    `MediaOccurrenceId` BIGINT UNSIGNED NULL,
    `EntityType` VARCHAR(32) NOT NULL,
    `EntityId` BIGINT UNSIGNED NOT NULL,
    `ChangeType` VARCHAR(32) NOT NULL,
    `ChangeDataJson` JSON NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_MediaChange_PublicId` (`PublicId`),
    KEY `Ix_MediaChange_User_Cursor` (`UserId`, `Id`),
    KEY `Ix_MediaChange_User_Source_Cursor` (`UserId`, `MediaSourceId`, `Id`),
    KEY `Ix_MediaChange_CreatedAt` (`CreatedAtUtc`),
    CONSTRAINT `Fk_MediaChange_UserAccount`
        FOREIGN KEY (`UserId`) REFERENCES `UserAccount` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `LegacyImageAssetMap` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `LegacyImageAssetId` BIGINT NOT NULL,
    `MediaAssetId` BIGINT UNSIGNED NULL,
    `MediaOccurrenceId` BIGINT UNSIGNED NULL,
    `MigrationStatus` VARCHAR(32) NOT NULL DEFAULT 'Pending',
    `FailureCode` VARCHAR(64) NULL,
    `FailureMessage` TEXT NULL,
    `TemporalReviewRequired` TINYINT(1) NOT NULL DEFAULT 0,
    `LastAttemptAtUtc` DATETIME(6) NULL,
    `MigratedAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_LegacyImageAssetMap_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_LegacyImageAssetMap_LegacyId` (`LegacyImageAssetId`),
    UNIQUE KEY `Ux_LegacyImageAssetMap_Occurrence` (`MediaOccurrenceId`),
    KEY `Ix_LegacyImageAssetMap_User_Status` (`UserId`, `MigrationStatus`, `UpdatedAtUtc`),
    CONSTRAINT `Fk_LegacyImageAssetMap_UserAccount`
        FOREIGN KEY (`UserId`) REFERENCES `UserAccount` (`Id`) ON DELETE CASCADE,
    CONSTRAINT `Fk_LegacyImageAssetMap_ImageAsset`
        FOREIGN KEY (`LegacyImageAssetId`) REFERENCES `ImageAsset` (`Id`) ON DELETE RESTRICT,
    CONSTRAINT `Fk_LegacyImageAssetMap_MediaAsset`
        FOREIGN KEY (`MediaAssetId`) REFERENCES `MediaAsset` (`Id`) ON DELETE SET NULL,
    CONSTRAINT `Fk_LegacyImageAssetMap_MediaOccurrence`
        FOREIGN KEY (`MediaOccurrenceId`) REFERENCES `MediaOccurrence` (`Id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
