CREATE TABLE IF NOT EXISTS `ManifestImport` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `MediaSourceId` BIGINT UNSIGNED NOT NULL,
    `SnapshotId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `IdempotencyKey` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `RequestSha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    `ActiveMarker` TINYINT UNSIGNED NULL DEFAULT 1,
    `ManifestKind` VARCHAR(16) NOT NULL,
    `PermissionState` VARCHAR(32) NOT NULL,
    `DeletionDetectionReliable` TINYINT(1) NOT NULL,
    `ClientCursor` VARCHAR(1024) NULL,
    `SchemaVersion` VARCHAR(32) NOT NULL,
    `Status` VARCHAR(32) NOT NULL DEFAULT 'AwaitingUpload',
    `Phase` VARCHAR(32) NOT NULL DEFAULT 'Preparing',
    `InputS3Bucket` VARCHAR(63) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `InputS3ObjectKey` VARCHAR(1024) COLLATE utf8mb4_bin NOT NULL,
    `InputS3VersionId` VARCHAR(1024) NULL,
    `InputChecksumSha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    `InputByteSize` BIGINT UNSIGNED NOT NULL,
    `DeclaredEntryCount` INT UNSIGNED NOT NULL,
    `ValidatedEntryCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `ProcessedEntryCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `CreatedCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `UpdatedCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `DuplicateLinkedCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `DeletedCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `IgnoredDeletionCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `UnchangedCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `RejectedCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `ResultS3Bucket` VARCHAR(63) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `ResultS3ObjectKey` VARCHAR(1024) COLLATE utf8mb4_bin NULL,
    `ResultChecksumSha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
    `ResultByteSize` BIGINT UNSIGNED NULL,
    `AttemptCount` INT UNSIGNED NOT NULL DEFAULT 0,
    `MaxAttempts` INT UNSIGNED NOT NULL DEFAULT 5,
    `NextAttemptAtUtc` DATETIME(6) NULL,
    `LeaseTokenHash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `LeaseExpiresAtUtc` DATETIME(6) NULL,
    `FailureClass` VARCHAR(32) NULL,
    `FailureCode` VARCHAR(64) NULL,
    `FailureMessage` TEXT NULL,
    `UploadExpiresAtUtc` DATETIME(6) NULL,
    `QueuedAtUtc` DATETIME(6) NULL,
    `StartedAtUtc` DATETIME(6) NULL,
    `CompletedAtUtc` DATETIME(6) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_ManifestImport_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_ManifestImport_User_Idempotency` (`UserId`, `IdempotencyKey`),
    UNIQUE KEY `Ux_ManifestImport_User_Source_Snapshot` (`UserId`, `MediaSourceId`, `SnapshotId`),
    UNIQUE KEY `Ux_ManifestImport_User_Source_Active` (`UserId`, `MediaSourceId`, `ActiveMarker`),
    UNIQUE KEY `Ux_ManifestImport_User_Id` (`UserId`, `Id`),
    KEY `Ix_ManifestImport_Status_NextAttempt` (`Status`, `NextAttemptAtUtc`, `Id`),
    KEY `Ix_ManifestImport_User_Source_Created` (`UserId`, `MediaSourceId`, `CreatedAtUtc`),
    CONSTRAINT `Fk_ManifestImport_MediaSource`
        FOREIGN KEY (`UserId`, `MediaSourceId`) REFERENCES `MediaSource` (`UserId`, `Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ManifestImportEntry` (
    `StageId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ManifestImportId` BIGINT UNSIGNED NOT NULL,
    `RowNumber` INT UNSIGNED NOT NULL,
    `OperationRaw` TEXT NOT NULL,
    `SourceItemIdRaw` TEXT COLLATE utf8mb4_bin NOT NULL,
    `SourceRevisionRaw` TEXT NULL,
    `OriginalFileNameRaw` TEXT NULL,
    `LocalLocatorRaw` LONGTEXT NULL,
    `ContentSha256Raw` TEXT NULL,
    `MediaTypeRaw` TEXT NULL,
    `MimeTypeRaw` TEXT NULL,
    `ByteSizeRaw` TEXT NULL,
    `WidthPixelsRaw` TEXT NULL,
    `HeightPixelsRaw` TEXT NULL,
    `DurationMillisecondsRaw` TEXT NULL,
    `CaptureDateTimeLocalRaw` TEXT NULL,
    `CaptureDateTimeUtcRaw` TEXT NULL,
    `TimeZoneRaw` TEXT NULL,
    `UtcOffsetMinutesRaw` TEXT NULL,
    `LatitudeRaw` TEXT NULL,
    `LongitudeRaw` TEXT NULL,
    `AltitudeMetersRaw` TEXT NULL,
    `AccuracyMetersRaw` TEXT NULL,
    `ProvenanceJsonRaw` LONGTEXT NULL,
    `Operation` VARCHAR(16) NULL,
    `SourceItemId` VARCHAR(512) COLLATE utf8mb4_bin NULL,
    `SourceRevision` VARCHAR(255) NULL,
    `OriginalFileName` VARCHAR(512) NULL,
    `LocalLocator` TEXT NULL,
    `ContentSha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
    `MediaType` VARCHAR(16) NULL,
    `MimeType` VARCHAR(255) NULL,
    `ByteSize` BIGINT UNSIGNED NULL,
    `WidthPixels` INT UNSIGNED NULL,
    `HeightPixels` INT UNSIGNED NULL,
    `DurationMilliseconds` BIGINT UNSIGNED NULL,
    `CaptureDateTimeLocal` DATETIME(6) NULL,
    `CaptureDateTimeUtc` DATETIME(6) NULL,
    `TimeZone` VARCHAR(64) NULL,
    `UtcOffsetMinutes` SMALLINT NULL,
    `Latitude` DECIMAL(9,6) NULL,
    `Longitude` DECIMAL(10,6) NULL,
    `AltitudeMeters` DECIMAL(10,3) NULL,
    `AccuracyMeters` DECIMAL(10,3) NULL,
    `CoordinateRevision` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `ProvenanceJson` JSON NULL,
    `LocationSource` VARCHAR(32) NULL,
    `ValidationState` VARCHAR(32) NOT NULL DEFAULT 'Pending',
    `ExistingOccurrenceId` BIGINT UNSIGNED NULL,
    `ExistingAssetId` BIGINT UNSIGNED NULL,
    `ResolvedAssetId` BIGINT UNSIGNED NULL,
    `Outcome` VARCHAR(32) NULL,
    `ErrorCode` VARCHAR(64) NULL,
    `ErrorMessage` VARCHAR(1000) NULL,
    `OccurrencePublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `MediaAssetPublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `DescriptionJobPublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`StageId`),
    UNIQUE KEY `Ux_ManifestImportEntry_Import_Row` (`ManifestImportId`, `RowNumber`),
    UNIQUE KEY `Ux_ManifestImportEntry_Import_Stage` (`ManifestImportId`, `StageId`),
    KEY `Ix_ManifestImportEntry_Import_SourceItem` (`ManifestImportId`, `SourceItemId`),
    KEY `Ix_ManifestImportEntry_Import_Hash` (`ManifestImportId`, `ContentSha256`),
    KEY `Ix_ManifestImportEntry_Import_ResolvedAsset` (`ManifestImportId`, `ResolvedAssetId`),
    CONSTRAINT `Fk_ManifestImportEntry_ManifestImport`
        FOREIGN KEY (`ManifestImportId`) REFERENCES `ManifestImport` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ManifestImportAssetWork` (
    `ManifestImportId` BIGINT UNSIGNED NOT NULL,
    `ContentSha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    `CanonicalStageId` BIGINT UNSIGNED NOT NULL,
    `CanonicalRowNumber` INT UNSIGNED NOT NULL,
    `ResolvedMediaAssetId` BIGINT UNSIGNED NULL,
    `ResolvedMediaAssetPublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `AssetWasPreexisting` TINYINT(1) NOT NULL DEFAULT 0,
    `AssetCreated` TINYINT(1) NOT NULL DEFAULT 0,
    `AssetChanged` TINYINT(1) NOT NULL DEFAULT 0,
    `ErrorCode` VARCHAR(64) NULL,
    `ErrorMessage` VARCHAR(1000) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UpdatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`ManifestImportId`, `ContentSha256`),
    KEY `Ix_ManifestImportAssetWork_Import_ResolvedAsset` (`ManifestImportId`, `ResolvedMediaAssetId`),
    KEY `Ix_ManifestImportAssetWork_CanonicalStage` (`ManifestImportId`, `CanonicalStageId`),
    CONSTRAINT `Fk_ManifestImportAssetWork_CanonicalEntry`
        FOREIGN KEY (`ManifestImportId`, `CanonicalStageId`)
        REFERENCES `ManifestImportEntry` (`ManifestImportId`, `StageId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ManifestImportFailure` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PublicId` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `UserId` BIGINT UNSIGNED NOT NULL,
    `ManifestImportId` BIGINT UNSIGNED NOT NULL,
    `RowNumber` INT UNSIGNED NOT NULL,
    `SourceItemId` VARCHAR(512) COLLATE utf8mb4_bin NOT NULL,
    `SourceRevision` VARCHAR(255) NULL,
    `Operation` VARCHAR(16) NOT NULL,
    `ErrorCode` VARCHAR(64) NOT NULL,
    `ErrorMessage` VARCHAR(1000) NULL,
    `CreatedAtUtc` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`Id`),
    UNIQUE KEY `Ux_ManifestImportFailure_PublicId` (`PublicId`),
    UNIQUE KEY `Ux_ManifestImportFailure_Import_Row` (`ManifestImportId`, `RowNumber`),
    KEY `Ix_ManifestImportFailure_User_Import` (`UserId`, `ManifestImportId`),
    CONSTRAINT `Fk_ManifestImportFailure_ManifestImport`
        FOREIGN KEY (`UserId`, `ManifestImportId`)
        REFERENCES `ManifestImport` (`UserId`, `Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `MediaOccurrence`
    ADD KEY `Ix_MediaOccurrence_User_Asset_DeletionState`
        (`UserId`, `MediaAssetId`, `DeletionState`),
    ALGORITHM=INPLACE,
    LOCK=NONE;
